Add files via upload
Quantum2Bits/GotoX pull request #1
Opened 2020-08-23 07:29 UTC by Quantum2Bits

2020-08-24 09:14 UTC, SeaHOH commented
你先把 gae.go 换成不使用 appengine 的版本，删除 gaej.go，那个用不了多久了。

然后我才好直接在代码中给你指出问题。

2020-08-24 09:39 UTC, Quantum2Bits commented
gae.go 换了

2020-08-24 11:38 UTC, SeaHOH reviewed
暂时就发现这些问题，你先修改试试能用不。

2020-08-24 11:38 UTC, SeaHOH commented on gae/app.yaml
> +runtime: go111
改成 go112

2020-08-24 11:38 UTC, SeaHOH commented on gae/gae.go
> +		log.Printf("binary.Read(&hdrLen) return %v", err)
改成 log.Printf 是因为 Context.Criticalf 无法使用吗，能否正确输出到云日志中？如果不能，其实这个功能可以去掉。

2020-08-24 11:38 UTC, SeaHOH commented on gae/gae.go
> +			//ResponseHeaderTimeout:        deadline,
取消这条注释，可以设置 ResponseHeaderTimeout。

2020-08-24 11:38 UTC, SeaHOH commented on gae/gae.go
>  		message := err.Error()
从这里开始的错误信息可能会有变化，之后再调试修改。

2020-08-24 11:38 UTC, SeaHOH commented on gae/gae.go
>  	req, _ := http.NewRequest("GET", "https://github.com/SeaHOH/GotoX/commits/gaeserver.goproxy/gae", nil)
如果不合入我的仓库，你可以修改为自己的仓库地址。

2020-08-24 11:38 UTC, SeaHOH commented on gae/gae.go
> +	//http.HandleFunc("/_gh/", handler)
这里直接调用 `init()`

2020-08-24 11:38 UTC, SeaHOH commented on gae/gae.go
> +`, runtime.Version(), runtime.GOOS, runtime.GOARCH, "jie-quanlin-app3.df.r.appspot.com", os.Getenv("GAE_ENV"), err.Error())
不要直接写 ID。
- 可以在上传前修改。
- 获取 `os.Getenv("GCP_PROJECT")` 值来组合。
- 使用 [Admin API apps.get](https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps/get) 获取主机名。

2020-08-25 08:01 UTC, Quantum2Bits commented
改了之后还是不行。客户端显示的错误：do_GAE 网关错误

2020-08-25 10:01 UTC, SeaHOH commented
设置 GotoX 代理后，直接访问 appid.appspot.com ，把返回页面内容贴一下。
估计是这里有问题，我看你 ID 的格式挺奇怪的，处于五级域名，可能无法返回内容。

2020-08-25 10:06 UTC, SeaHOH commented
对了，`log.Printf` 输出到 GCP 日志中了吗？

2020-08-25 10:13 UTC, SeaHOH commented on gae/gae.go
> +		fmt.Fprintf(rw,"%s \"%s %s %s\" %d %s", resp.Request.RemoteAddr, resp.Request.Method, resp.Request.URL.String(), resp.Request.Proto, resp.StatusCode, resp.Header.Get("Content-Length"))
这里使用 `log`

2020-08-26 07:27 UTC, Quantum2Bits commented
> 设置 GotoX 代理后，直接访问 appid.appspot.com ，把返回页面内容贴一下。
用代理没有反应。不用代理可以访问，很正常。
> 估计是这里有问题，我看你 ID 的格式挺奇怪的，处于五级域名，可能无法返回内容。
都一样，可以去df.r.
> 你的配置文件中，appid 填的是什么格式的 ID？
用的是绑定的域名，可以直接访问。

2020-08-26 07:28 UTC, Quantum2Bits commented
> 对了，`log.Printf` 输出到 GCP 日志中了吗？

去掉log也一样。没有查过log。

2020-08-26 07:34 UTC, Quantum2Bits commented
刚才上传了修改的版本，要好写。网页开始可以打开，但很快有出错了。主要是把http.Transport 移到了循环的外面，参数也做了设置。改了参数后就没有“do_GAE 网关错误”的信息了，但有“HTTP/1.1" 502 249”的错误。一道循环外部就能打开网页了。但还是有问题。

2020-08-26 09:12 UTC, SeaHOH commented
> 用的是绑定的域名，可以直接访问。

显示的内容是什么？

`RoundTrip` 这个操作不能重复使用，每次都要使用新对象，所以把它移动回循环中。

你又修改了 `init` 和 `main` 函数，`http.HandleFunc` 必须包含到 `main` 中，不管是直接还是间接调用。

记录日志的原因是为了调试，发生错误的话就能从云日志中看到到底是什么错误。

Go、Python、Node.js (Javascript)、PHP、Java 这些 GCP 支持的语言中你更熟悉哪个？考虑更换一个你擅长的。

2020-08-26 09:26 UTC, Quantum2Bits commented
> > 用的是绑定的域名，可以直接访问。
> 
> 显示的内容是什么？

{
"server": "goproxy r9999 (go1.13.15, linux/amd64)"
"latest": "2018-09-04T01:54:16Z",
"deploy": "2020-07-05T00:00:00Z",
"message": "already update to latest."
}

> 
> `RoundTrip` 这个操作不能重复使用，每次都要使用新对象，所以把它移动回循环中。
> 
> 你又修改了 `init` 和 `main` 函数，`http.HandleFunc` 必须包含到 `main` 中，不管是直接还是间接调用。
> 
> 记录日志的原因是为了调试，发生错误的话就能从云日志中看到到底是什么错误。
> 
> Go、Python、Node.js (Javascript)、PHP、Java 这些 GCP 支持的语言中你更熟悉哪个？考虑更换一个你擅长的。

只会c/c++ 做数值计算。网络编程是外行。

2020-08-26 10:50 UTC, SeaHOH commented
> "server": "goproxy r9999 (go1.13.15, linux/amd64)"

对不上啊，配置的是 1.12 吧。看起来是正确加载了 `http.HandleFunc("/", root)`。你这个信息对应的是哪个 commit？

> 只会c/c++ 做数值计算。网络编程是外行。

那你觉得上面哪个语言风格更符合你的想法习惯，就是 Go 吗？你可以花半个小时分别大概了解下。
关于网络编程，如果要稍微深入，就需要了解 HTTP 协议的原理，这样你写代码时就有更明确的目标，给你指出错误的时候也就大概清楚是为什么，而不至于搞不清状况。
日志对于调试来说非常重要，对于稍复杂的情况，有无日志可以说是天壤之别，可以节省非常多的时间。

另外，你为什么非执着于 GCP 呢？其它方式也可以简单地达到目的。没别的意思，只是看到你这么努力去弄自己不太擅长的东西。

2020-08-26 10:58 UTC, Quantum2Bits commented
go接近于c/c++。对GCP有点兴趣，原因说不上。能在GAE 上跑的服务，在其他的机器上也行吧。

2020-08-26 12:47 UTC, SeaHOH commented
是的，除了平台本身提供的服务外，其它自己编写的功能都可以正常运行。只需要将平台相关的特定函数、变量等修改为其等价普通形式，然后就可以按一般方式正常调用运行。

不过你这实在是太不熟练，你可以尝试先在本机实现一个使用 GotoX 的 GAE 代理协议的服务器，调试成功后再按照 GCP 文档修改成相应的格式。这样更方便，可以排除平台的干扰先保证所编写功能本身是正常的。

2020-08-27 07:55 UTC, Quantum2Bits commented
代码有上传了一遍，主要是调整了一点Transport的参数。用zebra勉强可以跑，用GotoX还是很bugy。

2020-08-27 09:04 UTC, SeaHOH commented on gae/gae.go
> +                       MaxIdleConns:          10,
Idle 这两项和下面的 TLSNextProto 都可以不用设置

2020-08-27 09:07 UTC, SeaHOH commented
> GotoX 经常说 Fetch Limit Full, timeout。

Limit Full 说明 IP 连接的质量很差，易丢包超时，这就是为什么「zebra勉强可以跑」。

2020-08-27 09:35 UTC, SeaHOH commented
> GotoX 经常说 Fetch Limit Full, timeout。

Limit Full 本身是指，当达到设置的连接数量上限时，已连接的请求中还没有任何一个顺利完成。这说明 IP 连接的质量很差，易丢包超时，这就是为什么「zebra勉强可以跑」。

你可以试试以下设置。
```ini
[gae]
appid =  # 使用绑定域名，切记一定要套一层 CDN
maxperip = 1  # 如果使用绑定域名，可以试试逐渐增加它
timeout = 15  # 15 - 30
keepalive = 0  # 0/1
keeptime = 30
maxrequsts =  # 如果使用的 APP 数量太少，设置为 10 除 APP 数量

# 如果使用绑定域名
[picker/gae]
enable = 0

# 如果使用 appid
[picker]
strict = 1
[picker/gae]
minrechecktime = 30  # 30 - 50
mincnt = 4  # 4 - 6
maxtimeout = 3000
maxthreads = 1  # 如果 data/ip_gae 包含的 IP 数量小于 100，可以先把它设置为 2 - 5，数量达到后改回 1 重启
```

2020-08-28 09:50 UTC, Quantum2Bits commented on gae/gae.go
> +                       MaxIdleConns:          10,
是可以去掉，但没有什么变化。我把新版本又上传了。

2020-08-28 09:58 UTC, Quantum2Bits commented
> > GotoX 经常说 Fetch Limit Full, timeout。
> 
> Limit Full 本身是指，当达到设置的连接数量上限时，已连接的请求中还没有任何一个顺利完成。这说明 IP 连接的质量很差，易丢包超时，这就是为什么「zebra勉强可以跑」。
> 
> 你可以试试以下设置。
> 
> ```ini
> [gae]
> appid =  # 使用绑定域名，切记一定要套一层 CDN
> maxperip = 1  # 如果使用绑定域名，可以试试逐渐增加它
> timeout = 15  # 15 - 30
> keepalive = 0  # 0/1
> keeptime = 30
> maxrequsts =  # 如果使用的 APP 数量太少，设置为 10 除 APP 数量
> 
> # 如果使用绑定域名
> [picker/gae]
> enable = 0
> 
> # 如果使用 appid
> [picker]
> strict = 1
> [picker/gae]
> minrechecktime = 30  # 30 - 50
> mincnt = 4  # 4 - 6
> maxtimeout = 3000
> maxthreads = 1  # 如果 data/ip_gae 包含的 IP 数量小于 100，可以先把它设置为 2 - 5，数量达到后改回 1 重启
> ```

要好一点，没有实质性的改善。服务器只要用appengine package，性能就好的多。去掉appengine package 后，handler() 里面只有一行代码变了（除了log外），就是把Transport变成了htpp.Transport。另外，用不用appengine package 对zebra似乎影响不是很大。

2020-08-28 10:11 UTC, Quantum2Bits commented
刚才查看了一下log，里面很多panic的信息。不是程序输出的。好像每个request都log了。

2020-08-28 11:58 UTC, SeaHOH requested changes

2020-08-28 11:58 UTC, SeaHOH commented on gae/gae.go
> +                       DialContext: netdial.DialContext,
你设置的参数过于严格，建议取消 `DialContext` 设置使用默认值。

2020-08-28 11:58 UTC, SeaHOH commented on gae/gae.go
> +		       //DialTLSContext:  tlsdial.DialContext,
1.14 以后使用 `DialTLSContext` 设置更好。

2020-08-28 11:58 UTC, SeaHOH commented on gae/gae.go
> +			fmt.Fprintf(os.Stderr,"URLFetchServiceError %T(%v) deadline=%v, url=%v", err, err, deadline, req.URL.String())
给这条记录加个标识字符串，和前面三条区分开，其 if 判断使用的字符串可能有变化，需要根据日志来修改。

2020-08-28 11:58 UTC, SeaHOH commented on gae/gae.go
> +	        port = "80"
APP 本身不直接对外服务，而是在 GCP 内部，相应端口是 8080。不过默认环境变量应该是有预设 8080，不会进入这个 if。

2020-08-28 11:59 UTC, SeaHOH commented
你绑定的域名套 CDN 没？

2020-08-29 07:01 UTC, Quantum2Bits commented
> 你绑定的域名套 CDN 没？

有一个套了。

2020-08-29 07:04 UTC, Quantum2Bits commented
刚上传了新版本，感觉搞好了，可以用了，和以前几乎差不多。这次把deadline和context都用上了，估计问题在这里。

2020-08-29 07:05 UTC, Quantum2Bits commented on gae/gae.go
> +                       DialContext: netdial.DialContext,
这是为了用context和deadline

2020-08-29 07:07 UTC, Quantum2Bits commented on gae/gae.go
> +		       //DialTLSContext:  tlsdial.DialContext,
感觉这是有用的

2020-08-29 07:13 UTC, Quantum2Bits commented on gae/gae.go
> +	        port = "80"
这是在本地用的

2020-08-29 07:49 UTC, SeaHOH commented on gae/gae.go
> +	defer cancel()
可能会快速消耗配额，不建议这么使用。

2020-08-29 07:51 UTC, SeaHOH commented on gae/gae.go
> +        s := &http.Server{
你这是本地服务？直接退出是什么意思？

2020-08-29 07:55 UTC, SeaHOH commented on gae/gae.go
> +		       //DialTLSContext:  tlsdial.DialContext,
这是 1.14 才开始提供的。

2020-08-29 07:59 UTC, SeaHOH commented on gae/gae.go
> +			fmt.Fprintf(os.Stderr,"URLFetchServiceError %T(%v) deadline=%v, url=%v", err, err, deadline, req.URL.String())
这几条错误信息都一样，不易区分，增加一个字符串，如 "Unknown"。

2020-08-29 08:01 UTC, SeaHOH commented
测试时使用套上 CDN 的域名，直连的 IP 质量太差。

2020-08-29 09:21 UTC, Quantum2Bits commented on gae/gae.go
> +		       //DialTLSContext:  tlsdial.DialContext,
去掉了

2020-08-29 09:22 UTC, Quantum2Bits commented on gae/gae.go
> +	defer cancel()
去掉了，好像是没用

2020-08-29 09:23 UTC, Quantum2Bits commented on gae/gae.go
> +        s := &http.Server{
这个也去掉了，好像有问题。

2020-08-29 09:26 UTC, Quantum2Bits commented
刚才用goproxy试了一下，感觉要好一些。网页能打开，文件上传没有成功。但GotoX还有问题。

2020-08-29 11:31 UTC, SeaHOH commented on gae/gae.go
> +		       //DialTLSContext:  tlsdial.DialContext,
`DialContext` 和 `DialTLSContext` 是可以同时设置的，只是后者需要 1.14。

2020-08-29 11:36 UTC, SeaHOH commented
超时设置不要太小。GotoX 还有什么问题？

2020-08-30 09:15 UTC, Quantum2Bits commented on gae/gae.go
> +			fmt.Fprintf(os.Stderr,"URLFetchServiceError %T(%v) deadline=%v, url=%v", err, err, deadline, req.URL.String())
加了

2020-08-30 09:30 UTC, Quantum2Bits commented
现在服务器的版本在Goproxy下基本可以用。而GotoX只能打开有些网页，很慢。但只要改两条代码，GotoX就变好了：把Transport用urlfetch的，在main里面加一句appengine.Main()。昨天看到GotoX很好，后来发现是用了appengine的版本。
所以感觉GotoX与现在的http.Transport不协调。比如对GotoX发出的request所出生的error信息与原来的不一致。另外，用http.client里的Do也不行，其error信息与Tranport不同。

2020-08-30 10:26 UTC, SeaHOH commented
可能和响应内容编码处理有关。如果提供两端相应的 debug 级别日志，我可以试着分析下具体原因。

2020-08-31 08:07 UTC, Quantum2Bits commented
16:01:59 E L4:40550->216.239.34.21 do_GAE "GET https://apnews.com/" 失败：timeout('The read operation timed out')
16:01:59 W L4:40562->[2001:4860:4802:34::15] do_GAE "GET https://apnews.com/dist/index.css?hash=1741f02cd85" 返回：timeout('The read operation timed out')，重试
16:02:05 E L4:40562->216.239.38.21 do_GAE "GET https://apnews.com/dist/index.css?hash=1741f02cd85" 失败：timeout('The read operation timed out')
Traceback (most recent call last):
  File "GotoX-3.6.1/local/compat/openssl.py", line 36, in __iowait
    return io_func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1840, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1646, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GotoX-3.6.1/local/ProxyHandler.py", line 941, in do_GAE
    response, data, need_chunked, _ = self.handle_response_headers(response)
  File "GotoX-3.6.1/local/ProxyHandler.py", line 512, in handle_response_headers
    data = response.read(self.bufsize)
  File "/usr/lib/python3.8/http/client.py", line 458, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "GotoX-3.6.1/local/compat/openssl.py", line 139, in recv_into
    return self.__iowait(self._connection.recv_into, buffer, nbytes, flags)
  File "GotoX-3.6.1/local/compat/openssl.py", line 42, in __iowait
    raise socket.timeout('The read operation timed out')
socket.timeout: The read operation timed out
----------------------------------------

  File "/usr/lib/python3.8/socket.py", line 666, in readinto
    raise OSError("cannot read from timed out object")
OSError: cannot read from timed out object
----------------------------------------
16:02:11 W L4:40582->216.239.34.21 do_GAE "GET https://apnews.com/dist/index.css?hash=1741f02cd85" 返回：timeout('The read operation timed out')，重试
16:02:16 E L4:40582->[2001:4860:4802:34::15] do_GAE "GET https://apnews.com/dist/index.css?hash=1741f02cd85" 失败：timeout('The read operation timed out')
Traceback (most recent call last):
  File "GotoX-3.6.1/local/compat/openssl.py", line 36, in __iowait
    return io_func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1840, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1646, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

During handling of the above exception, another exception occurred:


Exception happened during processing of request from ('127.0.0.1', 40582)

16:02:46 W L4:40600-> do_GAE "GET https://apnews.com/dist/index.css?hash=1741f02cd85" 返回：LimiterFull(-1, <class 'local.GAEFetch.LimitGAE'>)，重试

16:03:47 W L4:40658-> do_GAE "GET https://storage.googleapis.com/afs-prod/media/7e0f0c16251b468ab43795f2fb107ab9/400.jpeg" 返回：LimiterFull(-1, <class 'local.GAEFetch.LimitGAE'>)，重试
16:03:47 W L4:40654-> do_GAE "GET https://storage.googleapis.com/afs-prod/media/ca2de7631c9f4d0697565b41b6db11a1/800.jpeg" 返回：LimiterFull(-1, <class 'local.GAEFetch.LimitGAE'>)，重试
16:03:47 W L4:40648-> do_GAE "GET https://apnews.com/branding/favicon/256.png" 返回：LimiterFull(-1, <class 'local.GAEFetch.LimitGAE'>)，重试
16:03:47 W L4:40650-> do_GAE "GET https://apnews.com/branding/favicon/32.png" 返回：LimiterFull(-1, <class 'local.GAEFetch.LimitGAE'>)，重试
16:03:47 W L4:40652-> do_GAE "GET https://apnews.com/en_badge_web_generic.png" 返回：LimiterFull(-1, <class 'local.GAEFetch.LimitGAE'>)，重试
16:03:47 W L4:40660-> do_GAE "GET https://storage.googleapis.com/afs-prod/media/49c55ad4688e4207a060e73b44aad316/400.jpeg" 返回：LimiterFull(-1, <class 'local.GAEFetch.LimitGAE'>)，重试
16:03:47 W L4:40646-> do_GAE "GET https://apnews.com/dist/spritemap.svg" 返回：LimiterFull(-1, <class 'local.GAEFetch.LimitGAE'>)，重试
16:03:47 W L4:40656-> do_GAE "GET https://storage.googleapis.com/afs-prod/media/691564b30cf84d24b9fce8d0fceba0c1/400.jpeg" 返回：LimiterFull(-1, <class 'local.GAEFetch.LimitGAE'>)，重试
16:03:47 W L4:40664-> do_GAE "GET https://storage.googleapis.com/afs-prod/media/2ea26f59fa664cdcbbc8256f25487569/400.jpeg" 返回：LimiterFull(-1, <class 'local.GAEFetch.LimitGAE'>)，重试
16:03:47 W L4:40662-> do_GAE "GET https://storage.googleapis.com/afs-prod/media/02bd7ce473934e108ce74d1b9c3b3e96/400.jpeg" 返回：LimiterFull(-1, <class 'local.GAEFetch.LimitGAE'>)，重试

2020-08-31 08:15 UTC, Quantum2Bits commented
这是从GotoX输出的结果。服务端的log太多，找不出要的东西。另外在服务器里handler函数里包含Transport的循环由两次改为一次，GotoX的表现就好些，对Goproxy也没什么影响。第二次循环是把request做点修改后在来一遍，在http.Transport里面有问题，因为需要重新调试新的错误信息。总的感觉是http.Transport对GotoX的request理解的不太好，所以只能勉强打开某些网页。

2020-08-31 11:14 UTC, SeaHOH commented
似乎你没有使用套 CDN 那个域名来测试，超时设置好像也很小 ( 6? )，限制连接数也没调大 ( maxperip & maxrequsts )。。。

2020-08-31 11:26 UTC, SeaHOH commented
另外，谷歌相关网站建议直连或其它代理，而不要使用 GAE。

2020-09-01 10:17 UTC, Quantum2Bits commented
> 似乎你没有使用套 CDN 那个域名来测试，超时设置好像也很小 ( 6? )，限制连接数也没调大 ( maxperip & maxrequsts )。。。

改了之后效果有限，与用appengine package的表现不能比。

2020-09-01 10:25 UTC, Quantum2Bits commented
感觉问题出在对reponse的body的header的处理，这里有些appengine apckage的因数。其实zebra的服务其现在可以直接部署，GotoX用的很好。如果把这个服务器的appengine package去掉，并作相应的修改，它就不能用了。把GotoX的服务器里对reponse的body的header的处理做相应的替换之后就能用了。同样的是Goproxy表现好的多。

  感觉如果有客户端对reponse做处理，就稳健多了。否则，每次升级都要调试这里。

2020-09-01 12:21 UTC, SeaHOH commented
大部分处理都只能在远程服务端进行，即使转到本地服务端，升级后还是需要调试。你需要做的是查看远程错误日志，是否有不符合预期的，配合本地代理在浏览器做调试。

> 把GotoX的服务器里对reponse的body的header的处理做相应的替换之后就能用了。

如果可以，就替换它，我之前讲过会有变化，编码方式可能会有不同。因为之前 GAE fecth 这方面是有 bug 的，GotoX 与 zebra 的修复方法有区别。

2020-09-02 08:22 UTC, Quantum2Bits commented
刚才上传了修改的版本。把对reponse的处理去掉了，这样有明显的改善。goproxy基本正常了，可以上传文件了。GotoX对没有web socket的网页可以处理的比较好，但没有回到以前的表现，有点慢。估计因为没有用到appengine，也就不需要处理它的bug了。

如果对reponse的header不做压缩会不会好些？

2020-09-02 09:32 UTC, SeaHOH commented
对 reponse 的处理不要完全去掉，压缩环节可以保留以加快部分请求的响应速度。
不确定 `chunked` 为 `true` 时，响应是否被自动压缩，需要你自行调试以判断是否保留它。

GotoX 在恶劣条件下相对较慢是确定的，因为连接方式是 HTTP/1.x。

最后，是否仍然有编码不匹配的 bug，这需要你在之后的使用过程中观察。

> 如果对reponse的header不做压缩会不会好些？

这是个非常单纯的环节，没有理由不这么做。

2020-09-03 08:18 UTC, Quantum2Bits commented
上传了带压缩环节的版本，GotoX还是没有回到从前。

2020-09-03 09:53 UTC, SeaHOH commented on gae/gae.go
> +		       //DisableCompression:    true,
听说 `DisableCompression` 开启更好，你可以多比较下。

2020-09-03 09:54 UTC, SeaHOH commented
> 上传了带压缩环节的版本，GotoX还是没有回到从前。

这只在极少数情况下有用，原因不是它。上面说了可能是连接方式不同导致，但是近期我没有添加支持新连接方式的计划，所以使用 GotoX GAE 配 CDN 是有必要的。

2020-09-04 09:25 UTC, Quantum2Bits commented on gae/gae.go
> +		       //DisableCompression:    true,
开启了

2020-09-04 10:18 UTC, SeaHOH commented
折腾到现在，可满足基本使用了，把不需要的代码清理干净，暂告一段落。
然后点击下方 merge 按钮合并此 PR，还可以选择继续向 GotoX PR。

2020-09-05 08:43 UTC, merged

2020-09-05 08:44 UTC, Quantum2Bits commented
merge了

2020-09-05 09:46 UTC, SeaHOH commented
有问题再聊 :wave: